### PR TITLE
When the user tries to open more than 200 mnemonics the request fails

### LINKED ISSUE #365: 👉 When the user tries to open more than 200 mnemonics the request fails
**👉 Is your feature request related to a problem? Please describe.**
We allow the users to select all the mnemonics, but the get request fails when the URL is more than 2048 characters.
Related stories: #173, any story that relies on reading LogData

**Describe the solution you'd like**
Write an alternative POST endpoint, so we can send the mnemonics in the request body if the URL would be too long.

**Describe alternatives you've considered**
Not allowing the user to select that many mnemonics.

**Additional context**
Screenshot of the problem:
too_many_mnemonics

### PR DESCRIPTION
**Pull request by aszalos-roland**
# Request Template Witsml Explorer
Fixes #365

## Description
I created a GetLargeLogData Post endpoint in the API, on the client side if the URI is too long it will use this endpoint otherwise the already existing one.

## Type of change
- [x] Bugfix
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement of existing functionality
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Impacted Areas in Application
CurveValuesView, logObjectService

# Checklist:
- [x] PR is related to an issue
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have used descriptive naming on components, functions and variables to avoid additional explanatory comments in the code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Further comments
Do we need to keep the original endpoint and make a request like the current implementation, or can we remove the old endpoint and use only the Post implementation?

### CODE REVIEW

**Review by kdi-chandra — APPROVED** [review]
Changes looks good

**Review by steinsiv — COMMENTED** [review]
Works fine here, I left a comment on the GET/POST switch, maybe should use POST in all cases to simplify the codebase? What do you think?
There was a conflict in one file, when the conflict is cleared we can merge this 👍

**Review by HakonHesselberg — APPROVED** [review]
Tested and works locally. Looks good to me 🍪

**Comment by HakonHesselberg** [comment]
> Works fine here, I left a comment on the GET/POST switch, maybe should use POST in all cases to simplify the codebase? What do you think?

I think this should be considered, but it is out of scope for this PR. I think the PR should be merged once the conflict is solved and then we can make a separate issue for the get/post if necessary.

**Pull request merged**
