### PR TITLE
Sorting is wrong in some places

### LINKED ISSUE #398: 🐛 Sorting is wrong in the mnemonic ContentTable
**:bug: Describe the bug**
Sorting a column on the ContentTable uses an alphabetical sort order even when the column contains numbers. This seems like inappropriate behaviour to me.

**To Reproduce**
1. Go to a depth log
2. Sort by MinIndex
3. The column is not sorted as expected

**Expected behavior**
Columns with numerical data are sorted by using a numeric sort order.

**Screenshots**

Sort by MinIndex Asc:
sorting_is_wrong

Sort by MinIndex Desc:
sorting_is_wrong_2

**Desktop (please complete the following information):**
- any os, any browser
- found in main branch 

**Smartphone (please complete the following information):**
- any browser, any device
- found in main branch 

**Additional context**
no additional context

### PR DESCRIPTION
**Pull request by aszalos-roland**
# Request Template Witsml Explorer
Fixes #398 

## Description
Fixed sorting by adding a getComparatorByColumn function to tableParts.
This getComparatorByColumn  is now used in ContentTable and VirtualizedContentTable when the sort order is changed.

## Type of change
- [x] Bugfix
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement of existing functionality
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Impacted Areas in Application
ContentTable, VirtualizedContentTable

# Checklist:
- [x] PR is related to an issue
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have used descriptive naming on components, functions and variables to avoid additional explanatory comments in the code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Further comments
orderBy now looks like this orderBy(props.data, getComparatorByColumn(sortedColumn), [sortOrder, sortOrder])
the double sortOrder at the end is needed by lodash

### CODE REVIEW

**Review by kdi-chandra — APPROVED** [review]
Looks good and working as expected

**Review by steinsiv — COMMENTED** [review]
The `minindex` and ´maxindex` sorting on mnemonic level is OK at my end now 👍 
But the headers has now shifted positions to wrong columns. Anyone else experience this?

Screenshot 2021-06-02 at 14 32 37

The sorting on Log level `startindex` is still not accurate, but that was maybe not the target in this PR?

Screenshot 2021-06-02 at 14 30 22

**Comment by aszalos-roland** [comment]
> The `minindex` and ´maxindex` sorting on mnemonic level is OK at my end now 👍
> But the headers has now shifted positions to wrong columns. Anyone else experience this?
> 
> Screenshot 2021-06-02 at 14 32 37
> 
> The sorting on Log level `startindex` is still not accurate, but that was maybe not the target in this PR?
> 
> Screenshot 2021-06-02 at 14 30 22

I don't know about the header positions, haven't noticed it yet on my side.

Regarding the 'startIndex' sorting it is sorted as a string because it is not a number as it contains the unit as well.

**Review by HakonHesselberg — APPROVED** [review]
Looks good to me in general, although there is a bigger issue with the data not being tagged as the correct type, as well as numbers sometimes containing strings. That's outside the scope of this PR though, so I think we should merge this and discuss to find a solution to bad data.

**Pull request merged**
