### PR TITLE
Add isActive icon to LogCurveInfoListView

### LINKED ISSUE #393: 👉 Visualise Active Curves
**👉 Is your feature request related to a problem? Please describe.**
This task is related to User Story #392

It is important for users to quickly and easily get an overview over which curves are active.

**Describe the solution you'd like**
A symbol indicating which curves are active, similar to wells, wellbores and logs.

### PR DESCRIPTION
**Pull request by HakonHesselberg**
# Request Template Witsml Explorer
Fixes #393

## Description
Added column to display if a curve is active. 

A curve is considered active if the log is flagged as objectGrowing AND:

- ~~Depth: Within 50 meters of the deepest curve~~ (will not be implemented)
- Time: Updated less than an hour ago

Other issues in this user story will make the depth and time thresholds customizable.

image

...

## Type of change
_Put an x in the boxes that apply. You can also fill these out after creating the PR._

- [ ] Bugfix
- [x] New feature (non-breaking change which adds functionality)
- [x] Enhancement of existing functionality
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Impacted Areas in Application
_List general components of the application that this PR will affect:_

* LogCurveInfoListView

# Checklist:
_Put an x in the boxes that are fulfilled._

- [x] PR is related to an issue
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have used descriptive naming on components, functions and variables to avoid additional explanatory comments in the code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by aszalos-roland — COMMENTED** [review]
This change would have an effect on the export story as well.
Do we need to export the isActive column?

**Comment by HakonHesselberg** [comment]
> This change would have an effect on the export story as well.
> Do we need to export the isActive column?

Not sure this is necessary. The isActive parameter is calculated runtime to display which curves are active based on soon-to-be modifiable parameters.

**Comment by aszalos-roland** [comment]
> > This change would have an effect on the export story as well.
> > Do we need to export the isActive column?
> 
> Not sure this is necessary. The isActive parameter is calculated runtime to display which curves are active based on soon-to-be modifiable parameters.

yea I was wrong, sorry it doesn't affect at all, not even the same screen my bad 😅

**Review by aszalos-roland — APPROVED** [review]

**Comment by HakonHesselberg** [comment]
Removed isActive on depth curves as it is unsure if the method for calculating isActive is reliable enough to be used. The rest of the code is still there, but for now it is no longer visible.

**Review by steinsiv — APPROVED** [review]
Ran tests, and checked functionality.

**Review by kdi-chandra — APPROVED** [review]
Looks good

**Pull request merged**
