### PR TITLE
Selecting multiple rows with shift is unreliable in VirtualizedContentTable

### LINKED ISSUE #382: 🐛 Selecting multiple rows with shift is unreliable in VirtualizedContentTable
**:bug: Describe the bug**
Does not select what the user sees if the order is different than the default. In code the unsorted data is used for selection which causes this behaviour.

**To Reproduce**
1. Open some mnemonics from a log
2. Order the table differently
3. Using shift + click select some rows
4. Selection is not the desired selection

**Expected behavior**
A selection happens to the wanted item range.

**Screenshots**
Behaviour:
selection bug

**Desktop (please complete the following information):**
 - any browser
 - main branch

**Smartphone (please complete the following information):**
 - any device
 - main branch

### LINKED ISSUE #394: 👉 When a log has a lot of mnemonics the app performance declines
**👉 Is your feature request related to a problem? Please describe.**
Open a log with more than 200 mnemonics, when it loads clicking around, selecting some rows, using the context menu and expanding tree items take a lot more time than they should.

**Describe the solution you'd like**
Render a VirtualizedContent table instead of the ContentTable if there are more than 200 rows present.

**Describe alternatives you've considered**
Add pagination feature to the ContentTable.

**Additional context**
Perfomance gain is possible even with the current ContentTable, but as the OperationContext changes frequently it triggers a re-render of the ContentTable even when the state change is not related to the ContentTable ex.: triggering context menu (triggering context menu generates new coords thus generates a new state). The solution to this would be replacing the often used context states with custom hooks, narrowing down the OperationContext or separating the OperationContext.

### PR DESCRIPTION
**Pull request by aszalos-roland**
# Request Template Witsml Explorer
Fixes #382
Fixes #394 partially

## Description
The data handling is now similar to ContentTable and the selection works now in any case.
Moved innerGridElementType, Row functions out of VirtualizedContentTable as they did not belong in this function and for performance reasons.

## Type of change
_Put an x in the boxes that apply. You can also fill these out after creating the PR._

- [x] Bugfix
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement of existing functionality
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Impacted Areas in Application
VirtualizedContentTable

# Checklist:
- [x] PR is related to an issue
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have used descriptive naming on components, functions and variables to avoid additional explanatory comments in the code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Further comments
no further comments

### CODE REVIEW

**Comment by marmid74** [comment]
I believe there are still some unexpected behaviour due to missing reset of activeIndexRange at toggleAllRows.
The snapshot below shows the values of activeIndexRange when following this pattern of click:

1) Click index 0 -> [0,0]
2) Click index 4 -> [4,4]
3) Click Toggle all (on) -> [4,4] (now all rows are checked)
4) Click Toggle all (off) -> [4,4] (now all rows are unchecked)
5) Click + Shift index 6 -> [4,6] 
However as the screenshot shows, you get an unexpected combination of checked/ unchecked rows.
image

**Comment by aszalos-roland** [comment]
> I believe there are still some unexpected behaviour due to missing reset of activeIndexRange at toggleAllRows.
> The snapshot below shows the values of activeIndexRange when following this pattern of click:
> 
> 1. Click index 0 -> [0,0]
> 2. Click index 4 -> [4,4]
> 3. Click Toggle all (on) -> [4,4] (now all rows are checked)
> 4. Click Toggle all (off) -> [4,4] (now all rows are unchecked)
> 5. Click + Shift index 6 -> [4,6]
>    However as the screenshot shows, you get an unexpected combination of checked/ unchecked rows.
>    image

commited a fix for this

**Review by kdi-chandra — APPROVED** [review]
Looks good. working as expected

**Review by marmid74 — APPROVED** [review]
Works with expected behaviour, tests run. Looks good. Approves.

**Pull request merged**
