### PR TITLE
#1805 -  improved table view

### LINKED ISSUE #1827: Improved table view - sticky column and highlight of selected rows
**Is your feature request related to a problem? Please describe.**
Userstory: #1805 

**Describe the solution**

image

**
image
**

**Comments**
- GUI presented by ShellSquare to Equinor 17.th April
- Proposed enhancements for sticky columns and highlight of rows are accepted/approved by Equinor team

### PR DESCRIPTION
**Pull request by harigopalmg**
[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes

[//]: #1805 

This pull request fixes 

## Description
Improving table view design and functionality chnages

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [x] Enhancement of existing functionality

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [x] Frontend

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [x] PR affects application security

*Code quality*
* [x] I have self-reviewed my code
* [x] No new warnings are generated

*Test coverage*
* [x] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by janburak — CHANGES_REQUESTED** [review]
The improvements look good! Some comments:
- VirtualizedContentTable needs to be adjusted in the same way as ContentTable
- I am unsure whether the second column in ContentTable should be sticky (it should be in VirtualizedContentTable at least). I have asked the POs and will update you with the answer.
- Borders of sticky columns get "left behind" when scrolling (picture)
image

**Comment by janburak** [comment]
I got an answer from POs that the second column should not be sticky in ContentTable, it should be sticky only in VirtualizedContentTable.

**Comment by basim-rauf** [comment]
> The improvements look good! Some comments:
> 
> * VirtualizedContentTable needs to be adjusted in the same way as ContentTable
> * I am unsure whether the second column in ContentTable should be sticky (it should be in VirtualizedContentTable at least). I have asked the POs and will update you with the answer.
> * Borders of sticky columns get "left behind" when scrolling (picture)
>   image

> I got an answer from POs that the second column should not be sticky in ContentTable, it should be sticky only in VirtualizedContentTable.

* I've adjusted VirtualizedContentTable to look like ContentTable.
* I've removed the sticky columns from ContentTable and made VirtualizedContentTable sticky.

**Comment by janburak** [comment]
The changes look good. One issue I found is that in the VirtualizedContentTable the columns stick only until the visible width of the table, after which they get left behind. Maybe using a [ScrollSync](https://bvaughn.github.io/react-virtualized/?component=ScrollSync#/components/ScrollSync) would solve the issue? Attaching a video showing the issue.
https://github.com/equinor/witsml-explorer/assets/66632214/fac9c5a1-13b3-4f2c-9b02-d26395c4e0a6

**Comment by basim-rauf** [comment]
> The changes look good. One issue I found is that in the VirtualizedContentTable the columns stick only until the visible width of the table, after which they get left behind. Maybe using a [ScrollSync](https://bvaughn.github.io/react-virtualized/?component=ScrollSync#/components/ScrollSync) would solve the issue? Attaching a video showing the issue. https://github.com/equinor/witsml-explorer/assets/66632214/fac9c5a1-13b3-4f2c-9b02-d26395c4e0a6

I tried using a ScrollSync but that wasn't fixing the issue so I dug a little deeper and fixed some css and got it working.

**Review by janburak — APPROVED** [review]
- [X] Read issue and PR
- [X] Pulled branch and manually tested
- [X] Verify that PR resolves issue
- [X] Reviewed the code

**Pull request merged**
