### PR TITLE
upgrade carter to v6

### LINKED ISSUE #1107: Upgrade Carter to v6
**Is your feature request related to a problem? Please describe.**
Carter v6 has been released

**Describe the solution you'd like**
The version 6 has some breaking changes at the interfaces. Therefore, some code changes are needed.

### PR DESCRIPTION
**Pull request by kongxy10**
## Fixes
This pull request fixes #1107

## Description
Upgrade Carter to v6;
switch to new WebApplication class in Program.cs

## Type of change
* Enhancement of existing functionality

## Impacted Areas in Application
_List general components of the application that this PR will affect:_
* Some code changes in backend

## Checklist:
_Please tick all the boxes or remove the ones that aren't needed and explain why_

*Communication*
* [ ] PR is related to an issue
* [ ] I have made corresponding changes to the documentation

*Code quality*
* [x] Code follows the style guidelines
* [x] I have self-reviewed my code
* [x] No new warnings are generated

*Test coverage*
* [x] Existing tests pass
* [ ] New code is covered by passing tests

### CODE REVIEW

**Review by steinsiv — APPROVED** [review]
This simplified things quite a bit, thanks!

**Comment by lindsve** [comment]
Saw this a bit late...

We have in our other projects replaced Carter with use of the new minimalist APIs in ASP.NET 6. These API are quite similar to the APIs in Carter and in our view makes Carter redundant

**Comment by kongxy10** [comment]
Sorry, abandoned this PR since bugs were spotted in the routing.  @lindsve Yes, it seem better to switch to native minimal APIs.

**Comment by steinsiv** [comment]
I agree on replacing Carter but until someone implement that, this update from Carter 5 to Carter 6 is an improvement in my view.

**Pull request closed without merging**
