### PR TITLE
allow configuration of port number of allowd origin in CORS policy

### LINKED ISSUE #1925: Support configuration of port number of allowed origin in CORS policy
**Is your feature request related to a problem? Please describe.**
The current CORS policy setting in backend only supports frontend to be deployed with port number 3000

**Describe the solution you'd like**
Make the port number in allowed origin setting also configurable, so that the frontend can be deployed with other port numbers

### PR DESCRIPTION
**Pull request by kongxy10**
[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes

[//]: # (Write the GitHub issue number starting with #, or, for Equinor only, the Jira issue number starting with WE-)

This pull request fixes #1925

## Description

This PR tries to make the port number of allowed origin in backend CORS policy configurable as well. So we can support the frontend to be deployed/assigned with port number other than 3000.

To reviewers: please be advised that I also modify the related configuration name from "Host" to "AllowedOrigin" to better fits the meaning of this configuration. I hope this name change has no impact on the application deployment in case it might also be set through the source other than appsetting.json 

[//]: # (Please include a written summary of the changes and which issue is fixed. List any dependencies that are required for this change._)

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [ ] Bugfix
* [ ] New feature (non-breaking change which adds functionality)
* [x] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [ ] Frontend
* [x] API
* [ ] WITSML
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [x] I have made corresponding changes to the documentation
* [x] PR affects application security

*Code quality*
* [x] I have self-reviewed my code
* [x] No new warnings are generated

*Test coverage*
* [ ] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by janburak** [comment]
Docker/README.md also mentions the use of Host so I guess it should be changed to AllowedOrigin there as well.
Other than that renaming existing configuration variables is a breaking change, given that internal configurations overwrite the one found in the repo.

**Comment by kongxy10** [comment]
@janburak Is the 'Host' configuration used other than backend CORS settings?

**Comment by janburak** [comment]
'Host' is most likely not used for anything else. I assume Docker/README.md refers to [CORS with SignalR](https://learn.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-7.0) when mentioning "setting up the notifications feed" with relation to the 'Host' value.

**Comment by kongxy10** [comment]
@janburak Is it OK to rename the configuration name back to "Host", while the runtime configuration overwrite change the value to the full origin name (host+port), e.g. http://localhost:3000?

**Comment by kongxy10** [comment]
@janburak Is it OK to rename back the configuration name back to "Host", while the runtime configuration overwrite change the value to the full origin name (host+port), e.g. http://localhost:3000?

**Comment by janburak** [comment]
Either "AllowedOrigin" or "Host" is fine. Having host+port instead of just host in the configuration should be fine as well, if that's what you mean.

**Comment by kongxy10** [comment]
@janburak Thanks for the comments. I have updated the documentation in Docker/README.md. Given both naming is OK, I would prefer 'AllowedOrigin' since it is more straightforward.

**Review by janburak — APPROVED** [review]
- [X] Read issue and PR
- [X] Pulled branch and manually tested
- [X] Verify that PR resolves issue
- [X] Reviewed the code

Thank you for the PR!

**Pull request merged**
